nc: 22  # Total number of classes

path: C:\Users\MSI\Documents\Thesis_Project\Automste_Testing_DeepSeek_Model\data
train: images/train
val: images/train

names:
  - First Name
  - Second Name
  - Age
  - Gender
  - Email
  - School Name
  - Address
  - City
  - Result
  - Sophea
  - Oudom
  - 21
  - Male
  - dom@gmail.com
  - Rupp
  - St.99 Hm20
  - P.Penh
  - pass
  - Som
  - soDana
  - Female
  - dana@gmail.com